Vagrant.configure(2) do |config|
   config.vm.box = "chad-thompson/ubuntu-trusty64-gui"

   config.vm.provider "virtualbox" do |vb|
     vb.gui = true
     vb.memory = "1024"
     vb.name = "Aalta"
     #Disable USB
     vb.customize ["modifyvm", :id, "--usb", "off"]
     vb.customize ["modifyvm", :id, "--usbehci", "off"]
   end
  
  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
    config.vm.provision "shell", inline: <<-SHELL
	#Install g++ utility
	sudo apt-get install -y g++

	# Install git utility
 	sudo apt-get install -y git

	cd /home/vagrant/Desktop/

	mkdir AaltaSourceCode
	cd AaltaSourceCode/

	# Get Scripts from github repository
	git clone https://github.com/SoftwareEngineeringToolDemos/FSE-2014-Aalta.git

	cd FSE-2014-Aalta/build-vm/
	sudo chmod +x commands.sh

	cp commands.sh ../../../commands.sh
	cp Aalta.desktop ../../../Aalta.desktop
	cp Readme.txt ../../../Readme.txt
	cp LICENSE.txt ../../../LICENSE.txt
	cp Installation.txt ../../../Installation.txt	
	cp AaltaAuthorDemonstration.desktop ../../../AaltaAuthorDemonstration.desktop
	cp AaltaDemoVideo.desktop ../../../AaltaDemoVideo.desktop
	

	sudo mkdir "/home/vagrant/.config/autostart"
	sudo cp Aalta.desktop /home/vagrant/.config/autostart/Aalta.desktop

	
	#Remove unused Launcher Applications
	sudo rm -f "/usr/share/applications/ubuntu-amazon-default.desktop"
	sudo rm -f "/usr/share/applications/ubuntu-software-center.desktop"

	sudo reboot

   SHELL
end

